// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBAyEewXXqdsikQ1YELRGmI3O-tKzwjPw',
    appId: '1:914479160781:web:002e8ffd74bc387eccb884',
    messagingSenderId: '914479160781',
    projectId: 'first-app-42fb3',
    authDomain: 'first-app-42fb3.firebaseapp.com',
    databaseURL: 'https://first-app-42fb3-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-42fb3.firebasestorage.app',
    measurementId: 'G-H2ZHFM3KFC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKfL4itX0aBLWHzuzv2_Jhcg8mSR4QxS4',
    appId: '1:914479160781:android:64edb4b5260b74b5ccb884',
    messagingSenderId: '914479160781',
    projectId: 'first-app-42fb3',
    databaseURL: 'https://first-app-42fb3-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-42fb3.firebasestorage.app',
  );
}
